### ISSUE TITLE
Headers differs and that is why hmac does not work

### ISSUE THREAD

**Issue by ghost** [CheckoutFinland/psp-api#26]
I'm using Postman and I see that received html headers differs from what I'm sending. How can I receive same headers so that hmac calculation can be success? Calculation is done with your example code.

Headers that is sent (only those starting with 'checkout'):
```
    [0] => checkout-account:375917
    [1] => checkout-algorithm:sha256
    [2] => checkout-method:POST
    [3] => checkout-nonce:5c8101d60c5ad
    [4] => checkout-timestamp:2019-03-07T11:34:46.904Z
```
And headers received:
```
    [0] => checkout-account:375917
    [1] => checkout-algorithm:sha256
    [2] => checkout-method:POST
    [3] => checkout-transaction-id:024a4980-40cd-11e9-96a0-b74d8a6e9059
```
You can see that there is a difference. Also message body is part of the calculation and it's differs too. Answer body contains payment method buttons. And I'm sending your example request json.

I'm using this url: https://api.checkout.fi/payments

**Comment by vesse** [comment]
Yes, the headers are not the same that you sent nor should they be. And the response payload is also not the same that you sent because the response contains the buttons to render in the web shop.

The response HMAC is calculated from the response values and it will not be the same as the HMAC of the request. The point of HMAC validation is that one can verify the response has not been tampered with.

HMAC calculation is done exactly the same way for both request and response. When sending, the web shop calculates the HMAC using the values they send, and Checkout API verifies the HMAC using the data received. When Checkout API responds, it calculates response HMAC using the values it sends in the response, and the web shop can (and should) verify that the `signature` matches data _received_.

You can find example HMAC implementations for Node and PHP from https://checkoutfinland.github.io/psp-api/#/examples?id=code-examples The same code can be used for both response and request HMAC calculation.
