### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by karisalo1** [CheckoutFinland/psp-api#39]
Hi,

is it possible to test Checkout API (https://checkoutfinland.github.io/psp-api/checkout-psp-api.yaml) from swagger editor? There seems to be CORS - issues. 

> Access to fetch at 'https://api.checkout.fi/payments?created=2018-03-08&status=approved&limit=10&page=2' from origin 'https://editor.swagger.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by vesse** [comment]
Hi,

Unfortunately we cannot enable CORS on the payment APIs due to security compliance, thus testing directly with Swagger UI is not possible. It would be pretty painful otherwise too as you'd need to calculate the HMAC signature for the requests to receive anything else than a `HTTP 401` from the server.
