### ISSUE TITLE
Shop-In-Shop Commission MerchantID Error

### ISSUE THREAD

**Issue by ievgenklymenko** [CheckoutFinland/psp-api#54]
Hi, I'm having this error when setting Shop-In-Shop with commission:

> "Invalid commission merchant. Commission merchant must be one of SiS merchant accounts"

I use these test credentials from new documentation:

> Aggregate merchant ID: 695861
> Aggregate secret key: MONISAIPPUAKAUPPIAS
> Shop-in-Shop merchant ID: 695874

Request body looks like these (shortened):
```
        $body = [
            ...
            'items' => [[
                ...
                'merchant' => 695874,
                'commission' => [
                     ...
                     'merchant' => 695861,
                ]
            ]]
        ];
```

Request is signed with:  695861 + MONISAIPPUAKAUPPIAS

If I try to change commission merchantID to a SiS merchantID (so the same as item merchant, 695874), it gives no error. But this is opposite from what I want, I want my aggregate shop to receive a commission, which is paid by the inner retailer shop.

Please help thank you!

**Comment by vesse** [comment]
Hi,

You cannot use the aggregate account as commission account because aggregate accounts are not settled, ie. you would not be paid. When you register for the production account we will set you up with a separate submerchant account for the commissions. Customer service will be happy to assist you with the setup. Integration wise you can proceed with the commission merchant being the test submerchant.

**Comment by ievgenklymenko** [comment]
Ok I see, so when I'm registering an aggregate account there will be separate merchantID to use for commisions.
Thank you for blazing fast response!
