### ISSUE TITLE
Better redirect and callback url documentation

### ISSUE THREAD

**Issue by niklasmannila** [CheckoutFinland/psp-api#70]
There should be some more detailed documentation about how to implement the URL endpoints. Currently we are using the same URL for both redirect and callback (which is probably wrong). But the documentation states the following:
"The URLs may be called multiple times. The merchant web shop must be able to handle multiple requests for the same purchase."

What does this mean and how should we handle a case where the redirect URL is being called multiple times? There have been occasions where the URL's are called several times, but there is really no way to reproduce this and therefore almost impossible to implement any actions to take when it happens. 

Lets say the redirect url is being triggered rapidly, the first trigger is still handling the payment status sent and doing actions accordingly. Then the same url is being triggered while the first is still working and has not yet redirected it forward. To clarify, we have created an own landing page that we always redirect to that handles the case depending on the parameters it receives from checkout. Our page knows that it is processing the same checkout-reference and checkout-status but it is uncertain what we should do when it is already being processed? Sounds like we really cant be redirecting anything since the previous process is already redirecting it?

**Comment by snekbaev** [comment]
I'm not affiliated with OP, was just passing by, so this is not the "support" answering.
You have two sets of URLs: main to redirect the client and another - webhooks. You will redirect only via the first one, for webhooks you can reply with just ok or non-ok depending on your current state of processing state. Webhook URLs will be invoked directly by OPCheckout and can be used as a backup for a scenario when client somehow might not be able to reach your endpoint due to, for example, connectivity issues. There's a delay parameter for webhooks, if set to 0 redirects and webhooks might be invoked nearly simultaneously. 

About your question regarding what if it's called multiple times from several places. You will need to have some way of figuring out whether you are already processing that order, say, your order entity has a status property which has values of New, ProcessingPayment, PaymentFailure, PaymentSuccessful etc. (these values really depend on your requirements). So, when your "success redirect url" or "success webhook url" are being invoked there you will first try to update order's status field from "New" to "ProcessingPayment", but you must update only if current status is "New" (extra condition for the WHERE clause). Now, if you managed to do that then you know you can process it and finalize. But if you failed to set it, then you need to analyze why. For example, if after you failed you can refetch the status and if it has a value of "ProcessingPayment" then you know that it's already being processed. If either of "PaymentFailure" or "PaymentSuccessful" - guess, that's obvious.

This is a very high level overview, in reality you will have to take into account which URL might be called first (if your webhook delay value is very low), handle other failures, poll for payment processing status while user has already landed back to your public site, figure out how to troubleshoot when client was charged but you've never received that information etc :)

**Comment by niklasmannila** [comment]
A huge thanks for this :) I think the problem for us might have been that we haven't taken use of the callbackDelay and therefore the callback might have been triggered before the redirect. This would explain the issue that occurred, very randomly and rarely though. Your help is greatly appreciated and it gave me a lot of new ideas and information about how to handle this situation.

Thank you again!

**Comment by cibelius** [comment]
Hi, and thanks for both niklasmannila for reporting the issue and snekbaev for helping on our behalf!

snekbaev's answer is spot on, the callback url work as a backup if the user is not successfully redirected back to the success URL on their browser (which might occur due to e.g. connectivity or security problems, when e.g. an anti-virus software blocks the redirect). Usually both the redirect url and the webhook url are eventually requested, and both can be requested more than once in some cases.

We apologize for taking so long to reply, we have unfortunately been neglecting the GitHub issues for the past year or so. We intend to pay more attention to our GitHub repo in the future.

I'll close the issue as you seem to have figured it out!
