### ISSUE TITLE
Legacy API is still up?

### ISSUE THREAD

**Issue by akx** [CheckoutFinland/psp-api#81]
[The documentation claims that the Legacy API will be shutdown in June 2020](https://www.checkout.fi/vinkkipankki/checkoutin-uudet-rajapinnat-mit%C3%A4-pit%C3%A4%C3%A4-tiet%C3%A4%C3%A4), with a [Final Shutdown](https://www.youtube.com/watch?v=9jK-NcRmVcw) on the 30th:

> 30.6.2020 Vanha rajapinta suljetaan lopullisesti

However, I'm perfectly able to run a payment using the test credentials using the legacy API. What's going on? :D

**Comment by cibelius** [comment]
Hi akx, and thanks for reporting the issue!

The documentation was updated prematurely, as we intended to bring down the legacy API last summer, but had to keep it around due to some merchants taking their time to migrate to the new APIs.

Even though the Legacy API is still accessible, it is not supported. The Legacy API will be shut down soon.

We apologize for taking so long to reply, we have unfortunately been neglecting the GitHub issues for the past year or so. We intend to pay more attention to our GitHub repo in the future.
